[package]
name = "y2023d07"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2023d07"
path = "src/07.rs"

[dependencies]
aoclib = "0.2.1"
itertools = "0.12.0"
lazy_static = "1.4.0"
counter = "0.5.7"
